[package]
name = "ez-bitset"
version = "0.1.0"
edition = "2021"
authors = ["Johannes Meintrup", "Manuel Penschuck"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitvec = "1.0.0"
num = "0.4.0"